name: pozitolk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+5

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # state management
  provider: ^6.1.2
  # navigation
  go_router: ^14.8.0
  # di
  get_it: ^8.0.3
  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.1
  # media
  flutter_svg: ^2.0.17
  # text style & text input
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  intl_phone_number_field: ^0.2.1
  intl_phone_field: ^3.2.0
  intl: ^0.20.2
  motion_tab_bar_v2: ^0.4.0
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  internet_connection_checker_plus: ^2.6.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  web_socket_channel: ^3.0.3
#  motion_tab_bar: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/countries/



  fonts:
    - family: MV-Crooker
      fonts:
#        - asset: assets/fonts/MV-Crooker.ttf
        - asset: assets/fonts/crooker.otf
#    - family: okk
#      fonts:
#        - asset: fonts/McLaren-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/pozitolk_icon.png"